[package]
name = "rl-breakout"
version = "0.2.0"
edition = "2021"
authors = ["Roman Krüger<bitmagier@mailbox.org>"]
description = "Machine Learning | Reinforcement Learning | Deep-Q-Learning | Breakout"

[dev-dependencies]
rstest = "0.16.0"

[dependencies]
log = "0.4"
simple_logger = "4"
itertools = "0.10"
egui = "0.21"
eframe = { version = "0.21", features = ["dark-light"] }
parry2d = "0.13"
nalgebra = "0.32"
tensorflow = { version = "0.20.0", features = ["tensorflow_gpu"] }
