[package]
name = "rl-breakout"
version = "0.2.0"
edition = "2021"
authors = ["Roman Krüger<bitmagier@mailbox.org>"]
description = "Machine Learning | Reinforcement Learning | Deep-Q-Learning | Breakout"
repository = "git@github.com:bitmagier/rl-breakout.git"

[dev-dependencies]
rstest = "0.17"

[dependencies]
log = "0.4"
simple_logger = "4"
# rustc-hash = "1.1"
itertools = "0.10"
lazy_static = "1.4"
egui = "0.21"
eframe = { version = "0.21", features = ["dark-light"] }
parry2d = "0.13"
nalgebra = "0.32"
tensorflow = { version = "0.20.0", features = ["tensorflow_gpu"] }
clap = { version = "4", features = ["derive"] }
