[package]
name = "pong-ai-study"
version = "0.1.0"
edition = "2021"
authors = ["Roman Krüger<bitmagier@mailbox.org>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# tensorflow = { version = "0", features = ["tensorflow_gpu"] }
egui = "0"
eframe = { version = "0", features = ["dark-light"] }
