[package]
name = "pong-ai-study"
version = "0.1.0"
edition = "2021"
authors = ["Roman Krüger<bitmagier@mailbox.org>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
rstest = "*"

[dependencies]
log = "*"
simple_logger = "*"
itertools = "*"
# tensorflow = { version = "0", features = ["tensorflow_gpu"] }
egui = "*"
eframe = { version = "*", features = ["dark-light"] }
parry2d = "*"
