[package]
name = "breakout-ai"
version = "0.2.0"
edition = "2021"
authors = ["Roman Krüger<bitmagier@mailbox.org>"]

[dev-dependencies]
rstest = "0"

[dependencies]
log = "0"
simple_logger = "4"
itertools = "0"
tensorflow = { version = "0", features = ["tensorflow_gpu"] }
egui = "0"
eframe = { version = "0", features = ["dark-light"] }
parry2d = "0"
